version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: OFS
    volumes:
      - ./sql/Create.sql:/docker-entrypoint-initdb.d/01_Create.sql
      - ./sql/Triggers.sql:/docker-entrypoint-initdb.d/02_Triggers.sql
    ports:
      - "3307:3306"
    command: --lower_case_table_names=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

  backend:
    image: tuthache/cs160proj-backend:latest
    container_name: backend
    restart: unless-stopped
    ports:
      - "3301:3301"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: OFS
    env_file:
      - ./backend/.env

  frontend:
    image: tuthache/cs160proj-frontend:latest
    container_name: frontend
    ports:
      - "3300:3300"
    depends_on:
      - backend
